### ISSUE TITLE
Warning: Undefined array key "uncategory helper.php on line 35

### ISSUE THREAD

**Issue by ssnobben** [weltonwms/joomla-wx-icons-panel#1]
Hi 

I installed WX Icons Panel V1.0.4 Joomla 3.9.28 php 8.0.9 and create one module with one category and publish this on front page but get this error message. It works without the category but not work when you have created one category then you get this error message:

Warning: Undefined array key "uncategory" in /home/public_html/modules/mod_iconspanelwx/helper.php on line 35

**Comment by weltonwms** [comment]
Fixed Warning in version 1.0.5. Thanks for the remark. any suggestion is welcome
